version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "22"
  jobs:
    post_install:
      - pip install uv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --link-mode=copy
      
    pre_build:
      # Run the script that autogenerates content before building the docs
      - "uv run python ngff_spec/pre_build.py"

    build:
      html: 
        - cd ngff_spec/ && jupyter book build --html --ci
        - mkdir -p $READTHEDOCS_OUTPUT
        - mv ./ngff_spec/_build/html $READTHEDOCS_OUTPUT
