name: Validation
on:
  push:
  pull_request:

jobs:
  validate:
    name: Validation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -mpip install --upgrade wheel tox
      - run: tox